name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        dotnet-version: [ '2.1.x', '3.1.x', '5.0' ]

    steps:
    - uses: actions/checkout@v2.3.4

    - name: .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal